### ISSUE TITLE
Add cherry_grove biome

### ISSUE THREAD

**Issue by SlimeDog** [SlimeDog/BiomeRemap#18]
**Is your feature request related to a problem? Please describe.**
New biome **cherry_grove** added in MC 1.19.4.

**Describe the solution you'd like**
- [x] Add link to default configuration files
```
# Default configuration: https://github.com/SlimeDog/BiomeRemap/wiki/Configuration
```
- [x] Add cherry_grove to biomemaps in configuration
```
biomemaps:
  snowbound:
    biomes:
      cherry_grove:
        replacement-biome: snowy_plains
  boilerroom:
    biomes:
      cherry_grove:
        replacement-biome: cherry_grove
```
- [ ] Implement cherry_grove in code, if any changes required
